"""'创建基本数据库'

Revision ID: 7653cb72994c
Revises: 
Create Date: 2020-04-26 21:24:45.125240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7653cb72994c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='',
               autoincrement=True)
    # ### end Alembic commands ###
